### ISSUE TITLE
Getting a timeout Request timeout to api.dc01.gamelockerapp.com/54.172.56.79:443 after 60000 ms

### ISSUE THREAD

**Issue by KopalliAditya** [VainGG/flicker#6]
Exception in thread "main" com.vain.flicker.api.FlickerException: java.util.concurrent.TimeoutException: Request timeout to api.dc01.gamelockerapp.com/54.172.56.79:443 after 60000 ms
	at com.vain.flicker.api.FlickerApi.forceGet(FlickerApi.java:78)
	at com.vain.flicker.api.FlickerApi.getPlayerByName(FlickerApi.java:42)
	at Auth1.main(Auth1.java:53)
Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException: Request timeout to api.dc01.gamelockerapp.com/54.172.56.79:443 after 60000 ms
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
	at com.vain.flicker.api.FlickerApi.forceGet(FlickerApi.java:71)
	... 2 more
Caused by: java.util.concurrent.TimeoutException: Request timeout to api.dc01.gamelockerapp.com/54.172.56.79:443 after 60000 ms
	at org.asynchttpclient.netty.timeout.TimeoutTimerTask.expire(TimeoutTimerTask.java:44)
	at org.asynchttpclient.netty.timeout.RequestTimeoutTimerTask.run(RequestTimeoutTimerTask.java:51)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:663)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:738)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:466)
	at java.lang.Thread.run(Thread.java:748)

**Comment by KopalliAditya** [comment]
CODE: 
    public static void main(String args[]) throws Exception{
    		FlickerAsyncApi flickerAsyncApi = new FlickerAsyncApi(jwtToken);
    		Player p=flickerAsyncApi.getPlayerByName("abhisruth",Shard.SEA).get();
    		System.out.println(p.toString());

	}
CONSOLE ERROR:
Exception in thread "main" java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException: Request timeout to api.dc01.gamelockerapp.com/52.7.125.226:443 after 60000 ms
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
	at zzz.main(zzz.java:11)
Caused by: java.util.concurrent.TimeoutException: Request timeout to api.dc01.gamelockerapp.com/52.7.125.226:443 after 60000 ms
	at org.asynchttpclient.netty.timeout.TimeoutTimerTask.expire(TimeoutTimerTask.java:44)
	at org.asynchttpclient.netty.timeout.RequestTimeoutTimerTask.run(RequestTimeoutTimerTask.java:51)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:663)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:738)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:466)
	at java.lang.Thread.run(Thread.java:748)

**Comment by DominicGunn** [comment]
Hey,

This seems like an API issue rather than a Flicker issue. Could you let me know what player name you're using?
